name: Deploy to GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download previous build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ./_site
        continue-on-error: true

      - name: Build site structure
        run: |
          mkdir -p _site/${{ github.ref_name }}
          cp -r index.html ru en _site/${{ github.ref_name }}/
          echo "<h1>Версии сайта:</h1>" > _site/index.html
          echo "<ul>" >> _site/index.html
          gh release list --json tagName --jq '.[] | "<li><a href=\"\(.tagName)/index.html\">\(.tagName)</a></li>"' >> _site/index.html
          echo "</ul>" >> _site/index.html
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload build artifact for next run
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: ./_site
          
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact for current deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4