name: Deploy to GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Скачиваем исходный код
      - name: Checkout source code
        uses: actions/checkout@v4

      # Шаг 2: Создаем папку для публикации с текущей версией
      - name: Build current version folder
        run: |
          VERSION=${GITHUB_REF##*/}
          mkdir -p build/$VERSION
          cp -r en ru index.html build/$VERSION/
      
      # Шаг 3: Публикуем сайт, сохраняя старые версии
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          # Указываем, что публиковать нужно содержимое папки ./build
          publish_dir: ./build
          # ВАЖНО: Сохраняем все файлы, которые уже были в ветке gh-pages
          keep_files: true
          # ВАЖНО: Включаем автоматическое создание index.html со списком всех папок (версий)
          enable_jekyll: true
          commit_message: "Deploy release ${{ github.ref_name }}"